const root = '/assets'

export const assets = {
  logo: `${root}/brand/around-wordmark.svg`,
  footerWordmark: `${root}/brand/footer-wordmark.svg`,
  city: `${root}/city/city.png`,
  pin: {
    rippleOuter: `${root}/pins/ripple-outer.svg`,
    rippleMid: `${root}/pins/ripple-mid.svg`,
    rippleInner: `${root}/pins/ripple-inner.svg`,
    rippleCore: `${root}/pins/ripple-core.svg`,
    body: `${root}/pins/pin-body.svg`,
    holeOuter: `${root}/pins/pin-hole-outer.svg`,
    holeInner: `${root}/pins/pin-hole-inner.svg`,
  },
  appIcon: `${root}/app/around-app-icon.png`,
  dynamicIsland: `${root}/device/dynamic-island.svg`,
  finalCity: `${root}/backgrounds/final-city.png`,
  arrowRight: `${root}/ui/arrow-right.svg`,
  scrollDot: `${root}/ui/scroll-dot.svg`,
  privacyShield: `${root}/ui/privacy-shield.svg`,
  clouds: {
    heroLeftMid: `${root}/clouds/hero-left-mid.png`,
    heroLeft: `${root}/clouds/hero-left.png`,
    heroRightMid: `${root}/clouds/hero-right-mid.png`,
    heroRight: `${root}/clouds/hero-right.png`,
    heroCenter: `${root}/clouds/hero-center.png`,
    cityTopLeft: `${root}/clouds/city-top-left.png`,
    cityTop: `${root}/clouds/city-top.png`,
    cityRight: `${root}/clouds/city-right.png`,
    cityBottomLeft: `${root}/clouds/city-bottom-left.png`,
    cityBottom: `${root}/clouds/city-bottom.png`,
    mobileLeft: `${root}/clouds/mobile-left.png`,
    mobileRightMid: `${root}/clouds/mobile-right-mid.png`,
    mobileRight: `${root}/clouds/mobile-right.png`,
    mobileCenter: `${root}/clouds/mobile-center.png`,
    mobileBottom: `${root}/clouds/mobile-bottom.png`,
  },
  labels: {
    cafe: `${root}/labels/cafe.svg`,
    job: `${root}/labels/job.svg`,
    community: `${root}/labels/community.svg`,
    shopping: `${root}/labels/shopping.svg`,
    arrow: `${root}/labels/callout-arrow.svg`,
  },
  social: {
    twitter: `${root}/social/twitter.svg`,
    instagram: `${root}/social/instagram.svg`,
    linkedin: `${root}/social/linkedin.svg`,
    youtube: `${root}/social/youtube.svg`,
    facebook: `${root}/social/facebook.svg`,
  },
}
